version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./backend/_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8889:8080
    depends_on:
      - app
    container_name: sanctum_nginx

  app:
    build:
      context: .
      dockerfile: backend/_docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: sanctum_back
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./backend/tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: sanctum
        MYSQL_ROOT_PASSWORD: vyazuti12345
    ports:
      - 8888:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: sanctum_db


  nginx_front:
      image: nginx:latest
      volumes:
        - ./:/var/www
        - ./frontend/_docker/nginx/conf.d:/etc/nginx/conf.d
      ports:
        - 8876:80
      depends_on:
        - app
      container_name: front_nginx

  front:
    build:
      context: .
      dockerfile: frontend/_docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: sanctum_front
